language: node_js
node_js:
  - 'node'

before_install: yarn global add grunt-cli

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
before_deploy:
  - ls -la

env:
  global:
    - ENCRYPTION_LABEL: '36eb7b9455f3'
    - COMMIT_AUTHOR_EMAIL: travis-ci@w3.org
